matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode8

language: cpp

addons:
  apt:
    packages:
    - build-essential
    - libglib2.0-dev
    - libgtk2.0-dev
    - libxtst-dev
    - libxss-dev
    - libpci-dev
    - libdbus-1-dev
    - libgconf2-dev
    - libgnome-keyring-dev
    - libnss3-dev
    - libasound2-dev
    - libpulse-dev
    - libudev-dev

before_install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  else
    if ! brew ls --version cmake &>/dev/null; then brew update && brew install cmake; fi
  fi
- cd ${TRAVIS_BUILD_DIR}
- cmake --version

install:
- git submodule init
- git submodule update
- mkdir out
- cd out
- cmake ..

script:
- make package
- md5sum libwebrtc*.tar.gz

deploy:
  provider: releases
  api_key:
    secure: UazaqOOoifs5xE/xw+tjVnFAkl6MMJeZSW7B0DXX0wnHorKM5K72q9Ms3JYvJIp6DDV3vIeX/Yv/WQCnfRkDDhcbLohGZoOj2X3q53RSfJiOq/iIyPiPTRmkk3jQRBOvXl5zLePNaXU2vBuSgcM8az+wGjxaDLUB+EebSGRHPbXrGSnDDHaNnmb4Zm7SZ2DpL5ubRDlLTHst7Jh7OigrIblYKNCzwEc7UQsFNzLnu7dyZT4hF2Y+2KYl/3vUUkUGxu0AxVG7zilnjJE7O5gX76r+SQXs151uWwZeH41NNPxRSod51LKQS/V/I4afjjTaYC5+9lSUdNkOpEGrxU+61hSJvNGxL6rTqfiBTAOiJdMR3u4OmF+B72O0nUUpsNtlkSPBK9402Z65LH/UI2BIJ/oMfkjNSzTNTHvB+n+18nFryzUmgEJ4CEy7Yx5HGO1vXCP4OsHGAu5YCkDGV2uVttiYHlm2qWgTY59cQt61h1saQWMwj6Uivhz8XrS86K0r/YAS30t+7+/xG6dneXgctM9oYjIbVCFnImsE30FpWlCJvGnJzo37wctbTQscHs5iuqjt1an7AhQgOTMQwmtyyg32D6N9e4n+RJA9pEj3Qtpi51LVD1cdCahbZ1l4bURlNueqfB3d4oZvr9o/QNjm+qH/FRUWjAmWtbBr16ZXfiA=
  file: libwebrtc-$TRAVIS_TAG-linux-x64.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: aisouard/libwebrtc
